# Generated by Django 3.1.2 on 2020-10-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwardapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='owner',
        ),
    ]
