# Generated by Django 3.1.2 on 2020-10-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardapp', '0002_auto_20201026_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
