# Generated by Django 3.1.2 on 2020-10-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwardapp', '0004_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
