# Generated by Django 3.1.2 on 2020-10-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwardapp', '0008_auto_20201027_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Username',
        ),
    ]
